In [36]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
%matplotlib inline

In [37]:
##Step 1: Read CSV File

imdb = pd.read_csv(r"C:\Users\karthik\Desktop\Introduction-to-Machine-Learning-master\Building a Movie Recommendation Engine\movie_dataset.csv")
imdb.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [38]:
imdb.describe()

index        budget             id   popularity       revenue  \
count  4803.000000  4.803000e+03    4803.000000  4803.000000  4.803000e+03   
mean   2401.000000  2.904504e+07   57165.484281    21.492301  8.226064e+07   
std    1386.651002  4.072239e+07   88694.614033    31.816650  1.628571e+08   
min       0.000000  0.000000e+00       5.000000     0.000000  0.000000e+00   
25%    1200.500000  7.900000e+05    9014.500000     4.668070  0.000000e+00   
50%    2401.000000  1.500000e+07   14629.000000    12.921594  1.917000e+07   
75%    3601.500000  4.000000e+07   58610.500000    28.313505  9.291719e+07   
max    4802.000000  3.800000e+08  459488.000000   875.581305  2.787965e+09   

           runtime  vote_average    vote_count  
count  4801.000000   4803.000000   4803.000000  
mean    106.875859      6.092172    690.217989  
std      22.611935      1.194612   1234.585891  
min       0.000000      0.000000      0.000000  
25%      94.000000      5.600000     54.000000  
50%     103.000000      6.200000    235.000000  
75%     118.000000      6.800000    737.000000  
max     338.000000     10.000000  13752.000000

In [39]:
imdb.columns

Index(['index', 'budget', 'genres', 'homepage', 'id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count', 'cast', 'crew', 'director'],
      dtype='object')

In [40]:
imdb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 24 columns):
index                   4803 non-null int64
budget                  4803 non-null int64
genres                  4775 non-null object
homepage                1712 non-null object
id                      4803 non-null int64
keywords                4391 non-null object
original_language       4803 non-null object
original_title          4803 non-null object
overview                4800 non-null object
popularity              4803 non-null float64
production_companies    4803 non-null object
production_countries    4803 non-null object
release_date            4802 non-null object
revenue                 4803 non-null int64
runtime                 4801 non-null float64
spoken_languages        4803 non-null object
status                  4803 non-null object
tagline                 3959 non-null object
title                   4803 non-null object
vote_average            4803 non-null fl

In [41]:
imdb.isnull().sum().sort_values(ascending=False)

homepage                3091
tagline                  844
keywords                 412
cast                      43
director                  30
genres                    28
overview                   3
runtime                    2
release_date               1
popularity                 0
budget                     0
id                         0
original_language          0
original_title             0
production_countries       0
production_companies       0
crew                       0
revenue                    0
spoken_languages           0
status                     0
title                      0
vote_average               0
vote_count                 0
index                      0
dtype: int64

In [42]:
features = ['keywords','cast','genres','director']

In [43]:
##Step 3: Create a column in DF which combines all selected features
for feature in features:
    imdb[feature] = imdb[feature].fillna('')
    
def combine_features(row):
    try:
        return row['keywords'] +" "+row['cast']+" "+row["genres"]+" "+row["director"]
    except:
        print ("Error:", row)

imdb["combined_features"] = imdb.apply(combine_features,axis=1)

imdb["combined_features"].head()

0    culture clash future space war space colony so...
1    ocean drug abuse exotic island east india trad...
2    spy based on novel secret agent sequel mi6 Dan...
3    dc comics crime fighter terrorist secret ident...
4    based on novel mars medallion space travel pri...
Name: combined_features, dtype: object

In [44]:
##Step 4: Create count matrix from this new combined column
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()
count_matrix=cv.fit_transform(imdb["combined_features"])
print(count_matrix.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [47]:
##Step 5: Compute the Cosine Similarity based on the count_matrix

from sklearn.metrics.pairwise import cosine_similarity
cos_sim= cosine_similarity(count_matrix)
#print(similarity_score)
movie_user_likes = "The Avengers"

In [48]:
## Step 6: Get index of this movie from its title

def get_title_from_index(index):
    return imdb[imdb.index == index]["title"].values[0]

def get_index_from_title(title):
    return imdb[imdb.title == title]["index"].values[0]


movie_index = get_index_from_title(movie_user_likes)
similar_movies =  list(enumerate(cos_sim[movie_index]))

## Step 7: Get a list of similar movies in descending order of similarity score
sorted_similar_movies = sorted(similar_movies,key=lambda x:x[1],reverse=True)

In [49]:
## Step 8: Print titles of first 50 movies
i=0
print("Top  similar movies like "+movie_user_likes+" are:\n")
for element in sorted_similar_movies:
    
    print(get_title_from_index(element[0]))
    i=i+1
    if i>50:
        break

Top  similar movies like The Avengers are:

The Avengers
Avengers: Age of Ultron
Iron Man 2
Captain America: The Winter Soldier
Captain America: Civil War
Thor: The Dark World
The Incredible Hulk
Ant-Man
X-Men
X2
Captain America: The First Avenger
X-Men: The Last Stand
X-Men: Days of Future Past
Iron Man 3
Iron Man
X-Men: Apocalypse
Thor
Deadpool
The Amazing Spider-Man 2
Man of Steel
Superman II
Guardians of the Galaxy
Spawn
The Spirit
X-Men: First Class
What's Your Number?
Batman v Superman: Dawn of Justice
Street Fighter: The Legend of Chun-Li
Watchmen
The Helix... Loaded
The Image Revolution
Fantastic Four
Sin City
X-Men Origins: Wolverine
A Scanner Darkly
Max Payne
London
The Hunger Games: Catching Fire
The Wolverine
Down to Earth
The Shadow
Money Train
2 Guns
Home Alone 2: Lost in New York
Beastmaster 2: Through the Portal of Time
Star Trek Into Darkness
Delgo
Teenage Mutant Ninja Turtles: Out of the Shadows
Star Trek Beyond
Star Trek
Red Sonja


In [17]:
imdb["vote_average"].unique()

array([ 7.2,  6.9,  6.3,  7.6,  6.1,  5.9,  7.4,  7.3,  5.7,  5.4,  7. ,
        6.5,  6.4,  6.2,  7.1,  5.8,  6.6,  7.5,  5.5,  6.7,  6.8,  6. ,
        5.1,  7.8,  5.6,  5.2,  8.2,  7.7,  5.3,  8. ,  4.8,  4.9,  7.9,
        8.1,  4.7,  5. ,  4.2,  4.4,  4.1,  3.7,  3.6,  3. ,  3.9,  4.3,
        4.5,  3.4,  4.6,  8.3,  3.5,  4. ,  2.3,  3.2,  0. ,  3.8,  2.9,
        8.5,  1.9,  3.1,  3.3,  2.2,  0.5,  9.3,  8.4,  2.7, 10. ,  1. ,
        2. ,  2.8,  9.5,  2.6,  2.4])

Now, we will again sort our sorted_similar_movies but this time with respect to vote_average. x[0] has the index of the movie in the data frame.

In [18]:
sort_by_average_vote = sorted(sorted_similar_movies,key=lambda x:imdb["vote_average"][x[0]],reverse=True)
print(sort_by_average_vote)

[(3519, 0.0), (4045, 0.0), (4247, 0.0), (4662, 0.0), (3992, 0.0), (2386, 0.043643578047198484), (1881, 0.0), (2970, 0.0), (2796, 0.04082482904638631), (3337, 0.0), (3232, 0.044721359549995794), (2294, 0.04170288281141496), (662, 0.0), (1818, 0.0), (2731, 0.0), (3865, 0.0), (4755, 0.0), (1990, 0.08164965809277262), (65, 0.07844645405527362), (2170, 0.044721359549995794), (4535, 0.044721359549995794), (1987, 0.043643578047198484), (2247, 0.04264014327112209), (690, 0.0), (809, 0.0), (1663, 0.0), (1847, 0.0), (2947, 0.0), (3057, 0.0), (3719, 0.0), (3723, 0.0), (4602, 0.0), (96, 0.11766968108291043), (3573, 0.08728715609439697), (2912, 0.08528028654224418), (329, 0.08164965809277262), (2284, 0.04588314677411235), (2760, 0.043643578047198484), (1553, 0.04264014327112209), (3454, 0.04170288281141496), (3622, 0.04170288281141496), (2091, 0.04000000000000001), (95, 0.03849001794597506), (2453, 0.0), (3041, 0.0), (3788, 0.0), (3866, 0.0), (3906, 0.0), (4238, 0.0), (4302, 0.0), (262, 0.085280286

In [19]:
i=0
print("Suggesting top 5 movies in order of Average Votes:\n")
for element in sort_by_average_vote:
    print(get_title_from_index(element[0]))
    i=i+1
    if i>5:
        break

Suggesting top 5 movies in order of Average Votes:

Stiff Upper Lips
Dancer, Texas Pop. 81
Me You and Five Bucks
Little Big Top
Sardaarji
One Man's Hero
